# Generated by Django 3.2.15 on 2022-12-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=30)),
                ('away_team', models.CharField(max_length=30)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('sport', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
