# Generated by Django 3.2.15 on 2022-12-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbapredictions2022',
            name='away_points_pr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nbapredictions2022',
            name='away_points_pr_cum_me',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nbapredictions2022',
            name='away_points_pr_cum_rmse',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nbapredictions2022',
            name='home_points_pr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nbapredictions2022',
            name='home_points_pr_cum_me',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nbapredictions2022',
            name='home_points_pr_cum_rmse',
            field=models.FloatField(default=0.0),
        ),
    ]
