# Generated by Django 4.1.3 on 2022-12-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsApp', '0002_auto_20221201_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.TimeField(verbose_name='%H:%M'),
        ),
    ]
