# Generated by Django 3.2.15 on 2022-12-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsApp', '0002_auto_20221227_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbapredictions2022',
            name='away_points_eln',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nbapredictions2022',
            name='away_points_eln_cum_me',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nbapredictions2022',
            name='away_points_eln_cum_rmse',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nbapredictions2022',
            name='home_points_eln',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nbapredictions2022',
            name='home_points_eln_cum_me',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nbapredictions2022',
            name='home_points_eln_cum_rmse',
            field=models.FloatField(default=0.0),
        ),
    ]
