# Generated by Django 3.2.15 on 2022-12-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsApp', '0003_alter_schedule_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='away_city',
            field=models.CharField(default='hi', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='home_city',
            field=models.CharField(default='bye', max_length=30),
            preserve_default=False,
        ),
    ]
