# Generated by Django 3.2.15 on 2022-12-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsApp', '0003_auto_20221228_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbateam',
            name='alpha_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='best_fit_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='best_fit_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
