# Generated by Django 3.2.15 on 2022-12-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportsApp', '0004_auto_20221202_1424'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schedule',
            new_name='NBASchedule',
        ),
    ]
