# Generated by Django 3.2.15 on 2022-12-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsApp', '0005_rename_schedule_nbaschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbaschedule',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
