# Generated by Django 3.2.15 on 2022-12-05 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SportsApp', '0006_alter_nbaschedule_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NBATeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('sport', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='nbaschedule',
            name='away_city',
        ),
        migrations.RemoveField(
            model_name='nbaschedule',
            name='home_city',
        ),
        migrations.AlterField(
            model_name='nbaschedule',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='SportsApp.nbateam'),
        ),
        migrations.AlterField(
            model_name='nbaschedule',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='SportsApp.nbateam'),
        ),
    ]
