# Generated by Django 3.2.15 on 2022-12-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsApp', '0007_auto_20221205_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbateam',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
