# Generated by Django 3.2.15 on 2022-12-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsApp', '0008_alter_nbateam_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbaschedule',
            name='away_assists',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='away_blocks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='away_defReb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='away_fga',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='away_fgm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='away_fgp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='away_fta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='away_ftm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='away_ftp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='away_offReb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='away_pFouls',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='away_plusMinus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='away_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='away_steals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='away_totReb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='away_tpa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='away_tpm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='away_tpp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='away_turnovers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='home_assists',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='home_blocks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='home_defReb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='home_fga',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='home_fgm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='home_fgp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='home_fta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='home_ftm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='home_ftp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='home_offReb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='home_pFouls',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='home_plusMinus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='home_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='home_steals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='home_totReb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='home_tpa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='home_tpm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='home_tpp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='home_turnovers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbaschedule',
            name='played',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='assists_pg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='blocks_pg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='defReb_pg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='fga_pg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='fgm_pg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='fgp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='fta_pg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='ftm_pg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='ftp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='offReb_pg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='opp_assists_pg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='opp_blocks_pg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='opp_defReb_pg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='opp_fga_pg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='opp_fgm_pg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='opp_fgp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='opp_fta_pg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='opp_ftm_pg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='opp_ftp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='opp_offReb_pg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='opp_pFouls_pg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='opp_plusMinus_pg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='opp_points_pg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='opp_steals_pg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='opp_totReb_pg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='opp_tpa_pg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='opp_tpm_pg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='opp_tpp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='opp_turnovers_pg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='pFouls_pg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='plusMinus_pg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='points_pg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='steals_pg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='totReb_pg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='tpa_pg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='tpm_pg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='tpp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='turnovers_pg',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
