# Generated by Django 3.2.15 on 2022-12-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsApp', '0009_auto_20221205_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbateam',
            name='losses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='opp_losses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='opp_win_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='opp_wins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='win_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nbateam',
            name='wins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
