# Generated by Django 3.2.15 on 2022-12-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsApp', '0010_auto_20221205_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbateam',
            name='games',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
