# Generated by Django 3.2.15 on 2022-12-09 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SportsApp', '0012_auto_20221206_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='NBAHistoricalSchedule',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.TimeField(verbose_name='%H:%M')),
                ('date', models.DateField()),
                ('sport', models.CharField(max_length=10)),
                ('played', models.BooleanField(default='False')),
                ('home_points', models.IntegerField(blank=True, null=True)),
                ('home_fgm', models.IntegerField(blank=True, null=True)),
                ('home_fga', models.IntegerField(blank=True, null=True)),
                ('home_fgp', models.FloatField(blank=True, null=True)),
                ('home_ftm', models.IntegerField(blank=True, null=True)),
                ('home_fta', models.IntegerField(blank=True, null=True)),
                ('home_ftp', models.FloatField(blank=True, null=True)),
                ('home_tpm', models.IntegerField(blank=True, null=True)),
                ('home_tpa', models.IntegerField(blank=True, null=True)),
                ('home_tpp', models.FloatField(blank=True, null=True)),
                ('home_offReb', models.IntegerField(blank=True, null=True)),
                ('home_defReb', models.IntegerField(blank=True, null=True)),
                ('home_totReb', models.IntegerField(blank=True, null=True)),
                ('home_assists', models.IntegerField(blank=True, null=True)),
                ('home_pFouls', models.IntegerField(blank=True, null=True)),
                ('home_steals', models.IntegerField(blank=True, null=True)),
                ('home_turnovers', models.IntegerField(blank=True, null=True)),
                ('home_blocks', models.IntegerField(blank=True, null=True)),
                ('home_plusMinus', models.IntegerField(blank=True, null=True)),
                ('away_points', models.IntegerField(blank=True, null=True)),
                ('away_fgm', models.IntegerField(blank=True, null=True)),
                ('away_fga', models.IntegerField(blank=True, null=True)),
                ('away_fgp', models.FloatField(blank=True, null=True)),
                ('away_ftm', models.IntegerField(blank=True, null=True)),
                ('away_fta', models.IntegerField(blank=True, null=True)),
                ('away_ftp', models.FloatField(blank=True, null=True)),
                ('away_tpm', models.IntegerField(blank=True, null=True)),
                ('away_tpa', models.IntegerField(blank=True, null=True)),
                ('away_tpp', models.FloatField(blank=True, null=True)),
                ('away_offReb', models.IntegerField(blank=True, null=True)),
                ('away_defReb', models.IntegerField(blank=True, null=True)),
                ('away_totReb', models.IntegerField(blank=True, null=True)),
                ('away_assists', models.IntegerField(blank=True, null=True)),
                ('away_pFouls', models.IntegerField(blank=True, null=True)),
                ('away_steals', models.IntegerField(blank=True, null=True)),
                ('away_turnovers', models.IntegerField(blank=True, null=True)),
                ('away_blocks', models.IntegerField(blank=True, null=True)),
                ('away_plusMinus', models.IntegerField(blank=True, null=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team_hist', to='SportsApp.nbateam')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team_hist', to='SportsApp.nbateam')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
