# Generated by Django 3.2.15 on 2022-12-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsApp', '0016_auto_20221209_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbaschedule2022',
            name='away_linreg_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nbaschedule2022',
            name='home_linreg_points',
            field=models.FloatField(default=0.0),
        ),
    ]
