# Generated by Django 3.2.15 on 2022-12-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsApp', '0018_auto_20221214_0208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nbaschedule2017',
            old_name='played',
            new_name='boxscore_filled',
        ),
        migrations.RenameField(
            model_name='nbaschedule2018',
            old_name='played',
            new_name='boxscore_filled',
        ),
        migrations.RenameField(
            model_name='nbaschedule2019',
            old_name='played',
            new_name='boxscore_filled',
        ),
        migrations.RenameField(
            model_name='nbaschedule2020',
            old_name='played',
            new_name='boxscore_filled',
        ),
        migrations.RenameField(
            model_name='nbaschedule2021',
            old_name='played',
            new_name='boxscore_filled',
        ),
        migrations.RenameField(
            model_name='nbaschedule2022',
            old_name='played',
            new_name='boxscore_filled',
        ),
        migrations.AddField(
            model_name='nbaschedule2017',
            name='team_stats_filled',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='nbaschedule2018',
            name='team_stats_filled',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='nbaschedule2019',
            name='team_stats_filled',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='nbaschedule2020',
            name='team_stats_filled',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='nbaschedule2021',
            name='team_stats_filled',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='nbaschedule2022',
            name='team_stats_filled',
            field=models.BooleanField(default='False'),
        ),
    ]
