# Generated by Django 3.2.15 on 2022-12-17 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SportsApp', '0019_auto_20221216_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='NBAModelPredictions',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='SportsApp.nbaschedule2022')),
                ('home_points_lr', models.FloatField(default=0.0)),
                ('away_points_lr', models.FloatField(default=0.0)),
                ('home_points_lr_cum_rmse', models.FloatField(default=0.0)),
                ('away_points_lr_cum_rmse', models.FloatField(default=0.0)),
            ],
        ),
    ]
