# Generated by Django 3.2.15 on 2022-12-22 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SportsApp', '0020_nbamodelpredictions'),
    ]

    operations = [
        migrations.CreateModel(
            name='NBAOdds2022',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('home_spread', models.FloatField(default=0.0)),
                ('away_spread', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team_odds_2022', to='SportsApp.nbateam')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team_odds_2022', to='SportsApp.nbateam')),
            ],
        ),
    ]
