# Generated by Django 3.2.15 on 2022-12-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsApp', '0021_nbaodds2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbateam',
            name='full_name',
            field=models.CharField(default='name', max_length=40),
            preserve_default=False,
        ),
    ]
