# Generated by Django 3.2.15 on 2022-12-22 20:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SportsApp', '0022_nbateam_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbamodelpredictions',
            name='away_points_vegas',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nbamodelpredictions',
            name='away_points_vegas_rmse',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nbamodelpredictions',
            name='home_points_vegas',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nbamodelpredictions',
            name='home_points_vegas_rmse',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nbaodds2022',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
