# Generated by Django 3.2.15 on 2022-12-22 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportsApp', '0023_auto_20221222_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nbamodelpredictions',
            old_name='away_points_vegas_rmse',
            new_name='away_points_vegas_cum_rmse',
        ),
        migrations.RenameField(
            model_name='nbamodelpredictions',
            old_name='home_points_vegas_rmse',
            new_name='home_points_vegas_cum_rmse',
        ),
    ]
