# Generated by Django 3.2.15 on 2022-12-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsApp', '0024_auto_20221222_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbamodelpredictions',
            name='away_points_lr_cum_me',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nbamodelpredictions',
            name='away_points_vegas_cum_me',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nbamodelpredictions',
            name='home_points_lr_cum_me',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nbamodelpredictions',
            name='home_points_vegas_cum_me',
            field=models.FloatField(default=0.0),
        ),
    ]
