
NBA_TEAMS_DICT = {
    "Philadelphia" : "76ers",
    "Boston" : "Celtics",
    "LA Lakers" : "Lakers",
    "Golden State" : "Warriors",
    "Orlando" : "Magic",
    "Detroit" : "Pistons",
    "Washington" : "Wizards",
    "Indiana" : "Pacers",
    "Houston" : "Rockets",
    "Atlanta" : "Hawks",
    "New Orleans" : "Pelicans",
    "Brooklyn" : "Nets",
    "Chicago" : "Bulls",
    "Miami" : "Heat",
    "Cleveland" : "Caveliers",
    "Toronto" : "Raptors",
    "New York" : "Knicks",
    "Memphis" : "Grizzlies",
    "Okla City" : "Thunder",
    "Minnesota" : "Timberwolves",
    "Charlotte" : "Hornets",
    "San Antonio" : "Spurs",
    "Denver" : "Nuggets",
    "Utah" : "Jazz",
    "Dallas" : "Mavericks",
    "Phoenix" : "Suns",
    "Portland" : "Trailblazers",
    "Sacramento" : "Kings",
    "LA Clippers" : "Clippers",
    "Milwaukee" : "Bucks"
}

NBA_CITY_DICT = {
    "Philadelphia" : "Philadelphia",
    "Boston" : "Boston",
    "LA Lakers" : "Los Angeles",
    "Golden State" : "Golden State",
    "Orlando" : "Orlando",
    "Detroit" : "Detroit",
    "Washington" : "Washington",
    "Indiana" : "Indiana",
    "Houston" : "Houston",
    "Atlanta" : "Atlanta",
    "New Orleans" : "New Orleans",
    "Brooklyn" : "Brooklyn",
    "Chicago" : "Chicago",
    "Miami" : "Miami",
    "Cleveland" : "Cleveland",
    "Toronto" : "Toronto",
    "New York" : "New York",
    "Memphis" : "Memphis",
    "Okla City" : "Oklahoma City",
    "Minnesota" : "Minnesota",
    "Charlotte" : "Charlotte",
    "San Antonio" : "San Antonio",
    "Denver" : "Denver",
    "Utah" : "Utah",
    "Dallas" : "Dallas",
    "Phoenix" : "Phoenix",
    "Portland" : "Portland",
    "Sacramento" : "Sacramento",
    "LA Clippers" : "Los Angeles",
    "Milwaukee" : "Milwaukee"
}