from datetime import *

NBA_SEASON = 2022

NBA_SEASON_START_DATE_DICT = {
    '2022' : datetime.strptime("2022-10-18", '%Y-%m-%d'),
    '2021' : datetime.strptime("2021-10-19", '%Y-%m-%d'),
    '2020' : datetime.strptime("2020-12-22", '%Y-%m-%d'),
    '2019' : datetime.strptime("2019-10-22", '%Y-%m-%d'),
    '2018' : datetime.strptime("2018-10-16", '%Y-%m-%d'),
    '2017' : datetime.strptime("2017-10-17", '%Y-%m-%d'),
}

NBA_TEAMS_DICT = {
    "76ers"         : "Philadelphia"  ,
    "Celtics"       : "Boston"        ,
    "Lakers"        : "Los Angeles"   ,
    "Warriors"      : "Golden State"  ,
    "Magic"         : "Orlando"       ,
    "Pistons"       : "Detroit"       ,
    "Wizards"       : "Washington"    ,
    "Pacers"        : "Indiana"       ,
    "Rockets"       : "Houston"       ,
    "Hawks"         : "Atlanta"       ,
    "Pelicans"      : "New Orleans"   ,
    "Nets"          : "Brooklyn"      ,
    "Bulls"         : "Chicago"       ,
    "Heat"          : "Miami"         ,
    "Cavaliers"     : "Cleveland"     ,
    "Raptors"       : "Toronto"       ,
    "Knicks"        : "New York"      ,
    "Grizzlies"     : "Memphis"       ,
    "Thunder"       : "Oklahoma City" ,
    "Timberwolves"  : "Minnesota"     ,
    "Hornets"       : "Charlotte"     ,
    "Spurs"         : "San Antonio"   ,
    "Nuggets"       : "Denver"        ,
    "Jazz"          : "Utah"          ,
    "Mavericks"     : "Dallas"        ,
    "Suns"          : "Phoenix"       ,
    "Trail Blazers" : "Portland"      ,
    "Kings"         : "Sacramento"    ,
    "Clippers"      : "Los Angeles"   ,
    "Bucks"         : "Milwaukee"     
}

NBA_API_ID_DICT = {
    "76ers"         : 27   ,
    "Celtics"       : 2    ,
    "Lakers"        : 17   ,
    "Warriors"      : 11   ,
    "Magic"         : 26   ,
    "Pistons"       : 10   ,
    "Wizards"       : 41   ,
    "Pacers"        : 15   ,
    "Rockets"       : 14   ,
    "Hawks"         : 1    ,
    "Pelicans"      : 23   ,
    "Nets"          : 4    ,
    "Bulls"         : 6    ,
    "Heat"          : 20   ,
    "Cavaliers"     : 7    ,
    "Raptors"       : 38   ,
    "Knicks"        : 24   ,
    "Grizzlies"     : 19   ,
    "Thunder"       : 25   ,
    "Timberwolves"  : 22   ,
    "Hornets"       : 5    ,
    "Spurs"         : 31   ,
    "Nuggets"       : 9    ,
    "Jazz"          : 40   ,
    "Mavericks"     : 8    ,
    "Suns"          : 28   ,
    "Trail Blazers" : 29   ,
    "Kings"         : 30   ,
    "Clippers"      : 16   ,
    "Bucks"         : 21     
}

NBA_STAT_NAMES_LIST = ["PPG","FGM","FGA","FG%","FTM","FTA","FT%","3PM",
                       "3PA","3P%","ORB","DRB","TRB","AST","PF","ST","TO",
                       "BK","+/-"]

NBA_LIN_REG_PREDICTORS_LIST = ['home_opp_win_pct', 'home_fgm_pg', 'home_fga_pg', 'home_fgp',
       'home_ftm_pg', 'home_ftp', 'home_tpm_pg', 'home_tpp', 'home_offReb_pg',
       'home_defReb_pg', 'home_assists_pg', 'home_steals_pg',
       'home_turnovers_pg', 'home_blocks_pg', 'home_plusMinus_pg',
       'home_opp_fgm_pg', 'home_opp_fga_pg', 'home_opp_fgp', 'home_opp_ftm_pg',
       'home_opp_ftp', 'home_opp_tpm_pg', 'home_opp_tpp', 'home_opp_offReb_pg',
       'home_opp_defReb_pg', 'home_opp_assists_pg', 'home_opp_pFouls_pg',
       'home_opp_steals_pg', 'home_opp_turnovers_pg', 'home_opp_blocks_pg',
       'away_opp_win_pct', 'away_fgm_pg', 'away_fga_pg', 'away_fgp',
       'away_ftm_pg', 'away_ftp', 'away_tpm_pg', 'away_tpp', 'away_offReb_pg',
       'away_defReb_pg', 'away_assists_pg', 'away_steals_pg',
       'away_turnovers_pg', 'away_blocks_pg', 'away_plusMinus_pg',
       'away_opp_fgm_pg', 'away_opp_fga_pg', 'away_opp_fgp', 'away_opp_ftm_pg',
       'away_opp_ftp', 'away_opp_tpm_pg', 'away_opp_tpp', 'away_opp_offReb_pg',
       'away_opp_defReb_pg', 'away_opp_assists_pg', 'away_opp_pFouls_pg',
       'away_opp_steals_pg', 'away_opp_turnovers_pg', 'away_opp_blocks_pg']

NBA_TEAM_DB_STATS_FIELDS_LIST = ['points_pg','fgm_pg','fga_pg','fgp','ftm_pg','fta_pg',
                                 'ftp','tpm_pg','tpa_pg','tpp','offReb_pg','defReb_pg',
                                 'totReb_pg','assists_pg','pFouls_pg','steals_pg',
                                 'turnovers_pg','blocks_pg','plusMinus_pg','opp_points_pg',
                                 'opp_fgm_pg','opp_fga_pg','opp_fgp','opp_ftm_pg','opp_fta_pg',
                                 'opp_ftp','opp_tpm_pg','opp_tpa_pg','opp_tpp','opp_offReb_pg',
                                 'opp_defReb_pg','opp_totReb_pg','opp_assists_pg','opp_pFouls_pg',
                                 'opp_steals_pg','opp_turnovers_pg','opp_blocks_pg','opp_plusMinus_pg']
