
NBA_TEAMS_DICT = {
    "76ers"         : "Philadelphia"  ,
    "Celtics"       : "Boston"        ,
    "Lakers"        : "Los Angeles"   ,
    "Warriors"      : "Golden State"  ,
    "Magic"         : "Orlando"       ,
    "Pistons"       : "Detroit"       ,
    "Wizards"       : "Washington"    ,
    "Pacers"        : "Indiana"       ,
    "Rockets"       : "Houston"       ,
    "Hawks"         : "Atlanta"       ,
    "Pelicans"      : "New Orleans"   ,
    "Nets"          : "Brooklyn"      ,
    "Bulls"         : "Chicago"       ,
    "Heat"          : "Miami"         ,
    "Cavaliers"     : "Cleveland"     ,
    "Raptors"       : "Toronto"       ,
    "Knicks"        : "New York"      ,
    "Grizzlies"     : "Memphis"       ,
    "Thunder"       : "Oklahoma City" ,
    "Timberwolves"  : "Minnesota"     ,
    "Hornets"       : "Charlotte"     ,
    "Spurs"         : "San Antonio"   ,
    "Nuggets"       : "Denver"        ,
    "Jazz"          : "Utah"          ,
    "Mavericks"     : "Dallas"        ,
    "Suns"          : "Phoenix"       ,
    "Trail Blazers" : "Portland"      ,
    "Kings"         : "Sacramento"    ,
    "Clippers"      : "Los Angeles"   ,
    "Bucks"         : "Milwaukee"     
}