from django.db import models

class NBATeam(models.Model):
    id    = models.IntegerField(primary_key=True)
    name  = models.CharField(max_length=30)
    city  = models.CharField(max_length=30)
    sport = models.CharField(max_length=10)
    
    games       = models.IntegerField(default=0)
    wins        = models.IntegerField(default=0)
    losses      = models.IntegerField(default=0)
    win_pct     = models.FloatField(default=0.0)
    opp_wins    = models.IntegerField(default=0)
    opp_losses  = models.IntegerField(default=0)
    opp_win_pct = models.FloatField(default=0.0)

    points_pg    = models.FloatField(default=0.0)
    fgm_pg       = models.FloatField(default=0.0)
    fga_pg       = models.FloatField(default=0.0)
    fgp          = models.FloatField(default=0.0)
    ftm_pg       = models.FloatField(default=0.0)
    fta_pg       = models.FloatField(default=0.0)
    ftp          = models.FloatField(default=0.0)
    tpm_pg       = models.FloatField(default=0.0)
    tpa_pg       = models.FloatField(default=0.0)
    tpp          = models.FloatField(default=0.0)
    offReb_pg    = models.FloatField(default=0.0)
    defReb_pg    = models.FloatField(default=0.0)
    totReb_pg    = models.FloatField(default=0.0)
    assists_pg   = models.FloatField(default=0.0)
    pFouls_pg    = models.FloatField(default=0.0)
    steals_pg    = models.FloatField(default=0.0)
    turnovers_pg = models.FloatField(default=0.0)
    blocks_pg    = models.FloatField(default=0.0)
    plusMinus_pg = models.FloatField(default=0.0)

    opp_points_pg    = models.FloatField(default=0.0)
    opp_fgm_pg       = models.FloatField(default=0.0)
    opp_fga_pg       = models.FloatField(default=0.0)
    opp_fgp          = models.FloatField(default=0.0)
    opp_ftm_pg       = models.FloatField(default=0.0)
    opp_fta_pg       = models.FloatField(default=0.0)
    opp_ftp          = models.FloatField(default=0.0)
    opp_tpm_pg       = models.FloatField(default=0.0)
    opp_tpa_pg       = models.FloatField(default=0.0)
    opp_tpp          = models.FloatField(default=0.0)
    opp_offReb_pg    = models.FloatField(default=0.0)
    opp_defReb_pg    = models.FloatField(default=0.0)
    opp_totReb_pg    = models.FloatField(default=0.0)
    opp_assists_pg   = models.FloatField(default=0.0)
    opp_pFouls_pg    = models.FloatField(default=0.0)
    opp_steals_pg    = models.FloatField(default=0.0)
    opp_turnovers_pg = models.FloatField(default=0.0)
    opp_blocks_pg    = models.FloatField(default=0.0)
    opp_plusMinus_pg = models.FloatField(default=0.0)

    def __str__(self):
        return str(self.city) + ' ' + (self.name)

class NBASchedule(models.Model):
    id        = models.IntegerField(primary_key=True)
    home_team = models.ForeignKey(NBATeam, related_name="home_team", on_delete=models.CASCADE)
    away_team = models.ForeignKey(NBATeam, related_name="away_team", on_delete=models.CASCADE)
    time      = models.TimeField('%H:%M')
    date      = models.DateField()
    sport     = models.CharField(max_length=10)
    played    = models.BooleanField(default='False')

    home_points    = models.IntegerField(blank=True, null=True)
    home_fgm       = models.IntegerField(blank=True, null=True)
    home_fga       = models.IntegerField(blank=True, null=True)
    home_fgp       = models.FloatField(blank=True, null=True)
    home_ftm       = models.IntegerField(blank=True, null=True)
    home_fta       = models.IntegerField(blank=True, null=True)
    home_ftp       = models.FloatField(blank=True, null=True)
    home_tpm       = models.IntegerField(blank=True, null=True)
    home_tpa       = models.IntegerField(blank=True, null=True)
    home_tpp       = models.FloatField(blank=True, null=True)
    home_offReb    = models.IntegerField(blank=True, null=True)
    home_defReb    = models.IntegerField(blank=True, null=True)
    home_totReb    = models.IntegerField(blank=True, null=True)
    home_assists   = models.IntegerField(blank=True, null=True)
    home_pFouls    = models.IntegerField(blank=True, null=True)
    home_steals    = models.IntegerField(blank=True, null=True)
    home_turnovers = models.IntegerField(blank=True, null=True)
    home_blocks    = models.IntegerField(blank=True, null=True)
    home_plusMinus = models.IntegerField(blank=True, null=True)

    away_points    = models.IntegerField(blank=True, null=True)
    away_fgm       = models.IntegerField(blank=True, null=True)
    away_fga       = models.IntegerField(blank=True, null=True)
    away_fgp       = models.FloatField(blank=True, null=True)
    away_ftm       = models.IntegerField(blank=True, null=True)
    away_fta       = models.IntegerField(blank=True, null=True)
    away_ftp       = models.FloatField(blank=True, null=True)
    away_tpm       = models.IntegerField(blank=True, null=True)
    away_tpa       = models.IntegerField(blank=True, null=True)
    away_tpp       = models.FloatField(blank=True, null=True)
    away_offReb    = models.IntegerField(blank=True, null=True)
    away_defReb    = models.IntegerField(blank=True, null=True)
    away_totReb    = models.IntegerField(blank=True, null=True)
    away_assists   = models.IntegerField(blank=True, null=True)
    away_pFouls    = models.IntegerField(blank=True, null=True)
    away_steals    = models.IntegerField(blank=True, null=True)
    away_turnovers = models.IntegerField(blank=True, null=True)
    away_blocks    = models.IntegerField(blank=True, null=True)
    away_plusMinus = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return str(self.home_team) + " vs " + str(self.away_team) + " @ " + str(self.time)